name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
            PORT: 3000
            DBPORT: 3306
            DBHOST: 127.0.0.1
            DBUSER: root
            DBNAME: cazinoroial
            DBPASSWORD: Parola123!
            SESSIONSECRET: SessionSecret
          ports:
              - 3306
          options: 
            --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      PORT: 3000
      DBPORT: 3306
      DBHOST: localhost
      DBUSER: root
      DBNAME: cazinoroial
      DBPASSWORD: Parola123!
      SESSIONSECRET: SessionSecret
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Verify MySQL connection
      - run: |
          mysql --version
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u-u${{ env.DBUSER }} -p${{ env.DBPASSWORD }} -e "SHOW DATABASES"
      - run: sudo /etc/init.d/mysql start
      - run: mysql -h 127.0.0.1 --port 3306 -u${{ env.DBUSER }} -p${{ env.DBPASSWORD }} -e 'GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'; FLUSH PRIVILEGES;' 
      - run: mysql -u${{ env.DBUSER }} -p${{ env.DBPASSWORD }} -e 'CREATE DATABASE ${{ env.DBNAME }};' 
      - run: quit
      - run: sudo npm config set user 0
      - run: sudo npm config set unsafe-perm true
      - run: rm -Rf node_modules
      - run: npm install
      - run: sudo npm test
      - run: sudo node app.js
      - run: node app.js
      - run: npm test
