name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
            PORT: 3000
            DBPORT: 3306
            DBHOST: localhost
            DBUSER: root
            DBNAME: cazinoroial
            DBPASSWORD: Parola123!
            SESSIONSECRET: SessionSecret
          ports:
              - 3306
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: sudo npm config set user 0
      - run: sudo npm config set unsafe-perm true
      - run: sudo npm test
